config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :comments
  devise_for :users
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, length: {minimum: 1, maximum: 2000}
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_url(@comment.article_id), notice: 'Comment was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if @comment.user_id == current_user.id
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to controller: 'articles', action: 'show', id: @comment.article_id }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to article_url(@comment.article_id), notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_text, :article_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def get_user(comment)
    user = User.where(id: comment.user_id).first
    user.username
  end

  def get_avatar(user_id)
    user = User.where(id: user_id).first
    if user.avatar == ""
      img = "avatar.png"
    else
      user.avatar
    end
  end
end

app/views/comments/_comment.html.erb
<div id="comment_box">
  <div id="avatar">
    <%= image_tag get_avatar(comment.user_id) %>
  </div>
  <div id="content">
    <div id="comment_header">
      <span class="username"><%= get_user(comment) %></span> <%= comment.created_at.strftime("%d/%m/%Y %H:%M") %> <span class="comment_edit"><%= link_to 'Edit', edit_comment_path(comment) if user_signed_in? && current_user.id == comment.user_id %> <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? && current_user.id == comment.user_id %></span>
    </div>
    <div id="comment_text">
      <%= comment.comment_text %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(comment, remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_text %>
    <%= f.text_area :comment_text, :cols => 80 %>
    <%= f.hidden_field(:article_id) %>
  </div>

  <div class="actions">
    <%= f.submit "Wyślij" %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comment_box_form').before("<%=j render 'comments/comment', comment: @comment %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
<% end %>
<% if user_signed_in? %>
<div id="comment_box_form">
  <div id="avatar">
    <%= image_tag get_avatar(current_user.id) %>
  </div>
  <div id="content">
    <%= render 'comments/form', comment: @comment %>
  </div>
</div>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<p>
  <strong>Vote up:</strong>
  <%= @comment.vote_up %>
</p>

<p>
  <strong>Vote down:</strong>
  <%= @comment.vote_down %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>