config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :comments
  devise_for :users
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :description, :url, presence: true, uniqueness: true
  validates :title, length: {minimum: 10, maximum: 90}
  validates :description, length: {minimum: 50, maximum: 300}
  validates :url, :url => true
  validates :img, :url => true, allow_blank: true, format: { with: %r{.(jpg|png)\Z}i, message: 'must be a URL for JPG or PNG image.' }
  belongs_to :user
  has_many :comments
  has_many :votes
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  #before_action :set_comment, only: [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.reverse
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = Comment.where(article_id: params[:id]).all
    @comment = Comment.new
    @comment.article_id = params[:id]
    @vote = Vote.new
    #@vote.article_id = params[:id]
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.user_id == current_user.id
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @article.user_id == current_user.id
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      unless params[:article][:vote] == nil
        edit_vote_params
      end
      params.require(:article).permit(:title, :description, :url, :img, :vote, :vote_up, :vote_down)
    end

    def edit_vote_params
      if params[:article][:vote] == 'up'
        params[:article][:vote_up] = @article.vote_up + 1
      elsif params[:article][:vote] == 'down'
        params[:article][:vote_down] = @article.vote_down + 1
      end
      params[:article].delete :vote
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require 'uri'
  def get_host(url)
    uri = URI.parse(url)
    uri = URI.parse("http://#{url}") if uri.scheme.nil?
    host = uri.host.downcase
    host.start_with?('www.') ? host[4..-1] : host
  end

  def get_comments(article)
    comments = Comment.where(article_id: article.id).all.count
  end

  def get_user(article)
    user = User.where(id: article.user_id).first
    user.username
  end

  def get_img(article)
    if article.img == "" or article.img == nil
      img = "thumbnail.png"
    else
      article.img
    end
  end
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, size: 70 %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, size: 100 %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, size: 70 %>
  </div>

  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img, size: 70  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h3><%= link_to '>New Article<', new_article_path %></h3>

    <% @articles.each do |article| %>
    <div id="art_on_list">
      <div id="art_votes">
        <%= image_tag 'up.png', alt: 'Vote UP!' %>
        <br><span class="vote_up"><%= Vote.where(article_id: article.id, vote_type: true).count - Vote.where(article_id: article.id, vote_type: false).count %>
          <%= button_to "+", votes_path(@vote), params: {vote: {article_id: article.id, vote_type: true}}, :method => :post %></span>
      </div>
      <div id="art_img">
        <%= image_tag get_img(article), alt: article.title %>
      </div>
      <div id="art_info">
        <span class="art_title"><%= link_to article.title, article %></span><br>
        <span class="art_user">By <%= get_user(article) %></span>
        <span class="art_url">from <%= link_to get_host(article.url), article.url, target: "_blank" %></span> | <%= article.created_at.strftime("%d/%m/%Y %H:%M") %><br>
        <span class="art_description"><%= article.description %></span>
        <br><br><span class="art_comments">Comments: <%= get_comments(article) %></span>
      </div>
    </div>
    <% end %>

<br>

app/views/articles/new.html.erb
<div id="art_new">
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div id="art_view">
  <div id="art_votes">
    <div id="vote_up">
      <%= image_tag 'up.png', alt: 'Vote UP!' %>
      <br><span class="vote_up"><%= Vote.where(article_id: @article.id, vote_type: true).count %></span>
    </div>
    <%= button_to "+", votes_path(@vote), params: {vote: {article_id: @article.id, vote_type: true}}, :method => :post, remote: true %>
    <div id="vote_down">
      <span class="vote_down"><%= Vote.where(article_id: @article.id, vote_type: false).count %></span>
      <%= button_to "-", votes_path(@vote), params: {vote: {article_id: @article.id, vote_type: false}}, :method => :post, remote: true %>
      <%= image_tag 'down.png', alt: 'Vote DOWN!' %>
    </div>
  </div>
  <div id="art_view_img">
    <%= image_tag get_img(@article), alt: @article.title %>
  </div>
  <div id="art_view_info">
    <span class="art_title"><%= link_to @article.title, @article.url, target: "_blank" %></span><br>
    <span class="art_user">By <%= get_user(@article) %></span>
    <span class="art_url">from <%= link_to get_host(@article.url), @article.url, target: "_blank" %></span>
    <%= @article.created_at.strftime("%d/%m/%Y %H:%M") %> | <%= link_to 'Edit', edit_article_path(@article) if user_signed_in? && current_user.id == @article.user_id %><br>
    <span class="art_description"><%= @article.description %></span>
  </div>
</div>

<div id="comments_count">
  Comments: <%= get_comments(@article) %>
</div>

<%= render template: "comments/index" %>