config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :comments
  devise_for :users
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user_id, uniqueness: { scope: :article_id }
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    if Vote.exists?(user_id: current_user.id, article_id: params[:vote][:article_id])
      @vote = Vote.find_by(user_id: current_user.id, article_id: params[:vote][:article_id])
      update
    else
      @vote = current_user.votes.new(vote_params)
      respond_to do |format|
        if @vote.save
          format.html { redirect_to article_url(@vote.article_id), notice: 'Vote was successfully created.' }
          format.js
          format.json { render :show, status: :created, location: @vote }
        else
          format.html { render :new }
          format.json { render json: @vote.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    if @vote.user_id == current_user.id
      respond_to do |format|
        if @vote.update(vote_params)
          format.html { redirect_to article_url(@vote.article_id), notice: 'Vote was successfully updated.' }
          format.js
          format.json { render :show, status: :ok, location: @vote }
        else
          format.html { render :edit }
          format.json { render json: @vote.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    if @vote.user_id == current_user.id
      @vote.destroy
      respond_to do |format|
        format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:article_id, :vote_type)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(vote) do |f| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :article_id %>
    <%= f.text_field :article_id %>
  </div>

  <div class="field">
    <%= f.label :vote_type %>
    <%= f.check_box :vote_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/create.js.erb
$('.vote_up').html("<%= Vote.where(article_id: params[:vote][:article_id], vote_type: true).count %>");
$('.vote_down').html("<%= Vote.where(article_id: params[:vote][:article_id], vote_type: false).count %>");

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user_id %></td>
        <td><%= vote.article_id %></td>
        <td><%= vote.vote_type %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user_id %>
</p>

<p>
  <strong>Article:</strong>
  <%= @vote.article_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vote.vote_type %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>

app/views/votes/update.js.erb
$('.vote_up').html("<%= Vote.where(article_id: params[:vote][:article_id], vote_type: true).count %>");
$('.vote_down').html("<%= Vote.where(article_id: params[:vote][:article_id], vote_type: false).count %>");